config/routes.rb
Rails.application.routes.draw do
  resources :categories
  namespace :settings do
    resources :tags
  end
  get 'home/index'
  root to: "home#index"
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :User
end

app/models/settings.rb
module Settings
  def self.table_name_prefix
    'settings_'
  end
end

app/models/settings/tag.rb
class Settings::Tag < ApplicationRecord

end

app/models/todo_item.rb
class TodoItem < ApplicationRecord
  belongs_to :todo_list
end

app/models/todo_list.rb
class TodoList < ApplicationRecord
  has_many :todo_items
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:Title, :Color, :User_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index


  end
end

app/controllers/settings/tags_controller.rb
class Settings::TagsController < ApplicationController
  before_action :set_settings_tag, only: [:show, :edit, :update, :destroy]
  # GET /settings/tags
  # GET /settings/tags.json
  def index
    @settings_tags = Settings::Tag.all
  end

  # GET /settings/tags/1
  # GET /settings/tags/1.json
  def show
  end

  # GET /settings/tags/new
  def new
    @settings_tag = Settings::Tag.new
  end

  # GET /settings/tags/1/edit
  def edit
  end

  # POST /settings/tags
  # POST /settings/tags.json
  def create
    @settings_tag = Settings::Tag.new(settings_tag_params)
  @settings_tag.user = current_user
    respond_to do |format|
      if @settings_tag.save
        format.html { redirect_to @settings_tag, notice: 'Tag was successfully created.' }
        format.json { render :show, status: :created, location: @settings_tag }
      else
        format.html { render :new }
        format.json { render json: @settings_tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /settings/tags/1
  # PATCH/PUT /settings/tags/1.json
  def update
    respond_to do |format|
      if @settings_tag.update(settings_tag_params)
        format.html { redirect_to @settings_tag, notice: 'Tag was successfully updated.' }
        format.json { render :show, status: :ok, location: @settings_tag }
      else
        format.html { render :edit }
        format.json { render json: @settings_tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /settings/tags/1
  # DELETE /settings/tags/1.json
  def destroy
    @settings_tag.destroy
    respond_to do |format|
      format.html { redirect_to settings_tags_url, notice: 'Tag was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_settings_tag
    @settings_tag = Settings::Tag.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def settings_tag_params
    params.require(:settings_tag).permit(:title, :color)
  end
end

app/controllers/todo_items_controller.rb
class TodoItemsController < ApplicationController
  before_action :set_todo_list
  def create
    @todo_item = @todo_list.todo_items.create(todo_item_params)
    redirect_to @todo_list
  end
  def destroy
    @todo_item = @todo_list.todo_items.find(params[:id])
    if @todo_item.destroy
      flash[:success] = "Todo List item was deleted."
    else
      flash[:error] = "Todo List item could not be deleted."
    end
    redirect_to @todo_list
  end
  private
  def set_todo_list
    @todo_list = TodoList.find(params[:todo_list_id])
  end
  def todo_item_params
    params[:todo_item].permit(:content)
  end

  end

app/controllers/todo_lists_controller.rb
class TodoListsController < ApplicationController
  before_action :set_todo_list, only: [:show, :edit, :update, :destroy]

  # GET /todo_lists
  # GET /todo_lists.json
  def index
    @todo_lists = TodoList.all
  end

  # GET /todo_lists/1
  # GET /todo_lists/1.json
  def show
  end

  # GET /todo_lists/new
  def new
    @todo_list = TodoList.new
  end

  # GET /todo_lists/1/edit
  def edit
  end

  # POST /todo_lists
  # POST /todo_lists.json
  def create
    @todo_list = TodoList.new(todo_list_params)

    respond_to do |format|
      if @todo_list.save
        format.html { redirect_to @todo_list, notice: 'Todo list was successfully created.' }
        format.json { render :show, status: :created, location: @todo_list }
      else
        format.html { render :new }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todo_lists/1
  # PATCH/PUT /todo_lists/1.json
  def update
    respond_to do |format|
      if @todo_list.update(todo_list_params)
        format.html { redirect_to @todo_list, notice: 'Todo list was successfully updated.' }
        format.json { render :show, status: :ok, location: @todo_list }
      else
        format.html { render :edit }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todo_lists/1
  # DELETE /todo_lists/1.json
  def destroy
    @todo_list.destroy
    respond_to do |format|
      format.html { redirect_to todo_lists_url, notice: 'Todo list was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo_list
      @todo_list = TodoList.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def todo_list_params
      params.require(:todo_list).permit(:title, :string, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/settings/tags_helper.rb
module Settings::TagsHelper
end

app/helpers/todo_items_helper.rb
module TodoItemsHelper
end

app/helpers/todo_lists_helper.rb
module TodoListsHelper
end

app/views/categories/_form.html.erb
<%= simple_form_for(@category) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :Title %>
    <%= f.input :Color %>
    <%= f.association :User %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Categories</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Color</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.Title %></td>
        <td><%= category.Color %></td>
        <td><%= category.User %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @category.Title %>
</p>

<p>
  <strong>Color:</strong>
  <%= @category.Color %>
</p>

<p>
  <strong>User:</strong>
  <%= @category.User %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/home/index.html.erb
<h1>Nejvic</h1>
<p>Find me in app/views/home/index.html.erb</p>




<li><%= link_to "Tags", settings_tags_path , :class => "header" %></li>
  <li><%= link_to "Categories", new_category_path , :class => "header" %></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Nejvic</title>
    <%= csrf_meta_tags %>


    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <strong> User:</strong>

  </head>

  <body>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <ul>
  <li><%= link_to "Home",  home_index_path, :class => "header" %></li>
  <li><%= link_to "Register",  new_user_registration_path, :class => "header" %></li>
  <li><%= link_to "Log Out", destroy_user_session_path, method: :delete, :class => "header" %></li>
    <li><%= link_to "Log In",   user_session_path , :class => "header" %></li>
  <li><%= link_to "Edit Profile", edit_user_registration_path , :class => "header" %></li>


  </ul>
    <%= yield %>
  </body>
</html>

app/views/settings/tags/_form.html.erb
<%= simple_form_for(@settings_tag) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :color %>
   </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/settings/tags/edit.html.erb
<h1>Editing Settings Tag</h1>

<%= render 'form', settings_tag: @settings_tag %>

<%= link_to 'Show', @settings_tag %> |
<%= link_to 'Back', settings_tags_path %>

app/views/settings/tags/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Settings Tags</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Color</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @settings_tags.each do |settings_tag| %>
      <tr>
        <td><%= settings_tag.title %></td>
        <td><%= settings_tag.color %></td>
        <td><%= link_to 'Show', settings_tag %></td>
        <td><%= link_to 'Edit', edit_settings_tag_path(settings_tag) %></td>
        <td><%= link_to 'Destroy', settings_tag, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Settings Tag', new_settings_tag_path %>

app/views/settings/tags/new.html.erb
<h1>New Settings Tag</h1>

<%= render 'form', settings_tag: @settings_tag %>

<%= link_to 'Back', settings_tags_path %>

app/views/settings/tags/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @settings_tag.title %>
</p>

<p>
  <strong>Color:</strong>
  <%= @settings_tag.color %>
</p>

<p>
  <strong>User:</strong>
  <%= @settings_tag.user_id %>
</p>

<%= link_to 'Edit', edit_settings_tag_path(@settings_tag) %> |
<%= link_to 'Back', settings_tags_path %>

app/views/todo_items/_form.html.erb
<%= form_for([@todo_list, @todo_list.todo_items.build]) do |f| %>
  <%= f.text_field :content, placeholder: "New Todo" %>
  <%= f.submit %>
<% end %>

app/views/todo_items/_todo_item.html.erb
<p><%= todo_item.content %></p>
<%= link_to "Delete", todo_list_todo_item_path(@todo_list, todo_item.id), method: :delete, data: { confirm: "Are you sure?" } %>

app/views/todo_lists/_form.html.erb
<%= simple_form_for(@todo_list) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :string %>
    <%= f.input :description %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/todo_lists/edit.html.erb
<h1>Editing Todo List</h1>

<%= render 'form', todo_list: @todo_list %>

<%= link_to 'Show', @todo_list %> |
<%= link_to 'Back', todo_lists_path %>

app/views/todo_lists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Todo Lists</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>String</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @todo_lists.each do |todo_list| %>
      <tr>
        <td><%= todo_list.title %></td>
        <td><%= todo_list.string %></td>
        <td><%= todo_list.description %></td>
        <td><%= link_to 'Show', todo_list %></td>
        <td><%= link_to 'Edit', edit_todo_list_path(todo_list) %></td>
        <td><%= link_to 'Destroy', todo_list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Todo List', new_todo_list_path %>

app/views/todo_lists/new.html.erb
<h1>New Todo List</h1>

<%= render 'form', todo_list: @todo_list %>

<%= link_to 'Back', todo_lists_path %>

app/views/todo_lists/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>Title:</strong>
  <%= @todo_list.title %>
</p>
<p>
  <strong>Description:</strong>
  <%= @todo_list.description %>
</p>
<div id="todo_items_wrapper">
  <%= render @todo_list.todo_items %>
  <div id="form">
    <%= render "todo_items/form" %>
  </div>
</div>
<%= link_to 'Edit', edit_todo_list_path(@todo_list) %> |
<%= link_to 'Back', todo_lists_path %>